if(typeof elgg!='object'){throw new Error('elgg configuration object is not defined! You must include the js/initialize_elgg view in html head before JS library files!');}
var sprintf=(function(){function get_type(variable){return Object.prototype.toString.call(variable).slice(8,-1).toLowerCase();}
function str_repeat(input,multiplier){for(var output=[];multiplier>0;output[--multiplier]=input){}
return output.join('');}
var str_format=function(){if(!str_format.cache.hasOwnProperty(arguments[0])){str_format.cache[arguments[0]]=str_format.parse(arguments[0]);}
return str_format.format.call(null,str_format.cache[arguments[0]],arguments);};str_format.format=function(parse_tree,argv){var cursor=1,tree_length=parse_tree.length,node_type='',arg,output=[],i,k,match,pad,pad_character,pad_length;for(i=0;i<tree_length;i++){node_type=get_type(parse_tree[i]);if(node_type==='string'){output.push(parse_tree[i]);}
else if(node_type==='array'){match=parse_tree[i];if(match[2]){arg=argv[cursor];for(k=0;k<match[2].length;k++){if(!arg.hasOwnProperty(match[2][k])){throw(sprintf('[sprintf] property "%s" does not exist',match[2][k]));}
arg=arg[match[2][k]];}}
else if(match[1]){arg=argv[match[1]];}
else{arg=argv[cursor++];}
if(/[^s]/.test(match[8])&&(get_type(arg)!='number')){throw(sprintf('[sprintf] expecting number but found %s',get_type(arg)));}
switch(match[8]){case'b':arg=arg.toString(2);break;case'c':arg=String.fromCharCode(arg);break;case'd':arg=parseInt(arg,10);break;case'e':arg=match[7]?arg.toExponential(match[7]):arg.toExponential();break;case'f':arg=match[7]?parseFloat(arg).toFixed(match[7]):parseFloat(arg);break;case'o':arg=arg.toString(8);break;case's':arg=((arg=String(arg))&&match[7]?arg.substring(0,match[7]):arg);break;case'u':arg=Math.abs(arg);break;case'x':arg=arg.toString(16);break;case'X':arg=arg.toString(16).toUpperCase();break;}
arg=(/[def]/.test(match[8])&&match[3]&&arg>=0?'+'+arg:arg);pad_character=match[4]?match[4]=='0'?'0':match[4].charAt(1):' ';pad_length=match[6]-String(arg).length;pad=match[6]?str_repeat(pad_character,pad_length):'';output.push(match[5]?arg+pad:pad+arg);}}
return output.join('');};str_format.cache={};str_format.parse=function(fmt){var _fmt=fmt,match=[],parse_tree=[],arg_names=0;while(_fmt){if((match=/^[^\x25]+/.exec(_fmt))!==null){parse_tree.push(match[0]);}
else if((match=/^\x25{2}/.exec(_fmt))!==null){parse_tree.push('%');}
else if((match=/^\x25(?:([1-9]\d*)\$|\(([^\)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosuxX])/.exec(_fmt))!==null){if(match[2]){arg_names|=1;var field_list=[],replacement_field=match[2],field_match=[];if((field_match=/^([a-z_][a-z_\d]*)/i.exec(replacement_field))!==null){field_list.push(field_match[1]);while((replacement_field=replacement_field.substring(field_match[0].length))!==''){if((field_match=/^\.([a-z_][a-z_\d]*)/i.exec(replacement_field))!==null){field_list.push(field_match[1]);}
else if((field_match=/^\[(\d+)\]/.exec(replacement_field))!==null){field_list.push(field_match[1]);}
else{throw('[sprintf] huh?');}}}
else{throw('[sprintf] huh?');}
match[2]=field_list;}
else{arg_names|=2;}
if(arg_names===3){throw('[sprintf] mixing positional and named placeholders is not (yet) supported');}
parse_tree.push(match);}
else{throw('[sprintf] huh?');}
_fmt=_fmt.substring(match[0].length);}
return parse_tree;};return str_format;})();var vsprintf=function(fmt,argv){argv.unshift(fmt);return sprintf.apply(null,argv);};var elgg=elgg||{};elgg.global=this;elgg.ACCESS_PRIVATE=0;elgg.nullFunction=function(){};elgg.abstractMethod=function(){throw new Error("Oops... you forgot to implement an abstract method!");};elgg.extend=jQuery.extend;elgg.isArray=jQuery.isArray;elgg.isFunction=jQuery.isFunction;elgg.isPlainObject=jQuery.isPlainObject;elgg.isString=function(val){return typeof val==='string';};elgg.isNumber=function(val){return typeof val==='number';};elgg.isObject=function(val){return typeof val==='object';};elgg.isUndefined=function(val){return val===undefined;};elgg.isNull=function(val){return val===null;};elgg.isNullOrUndefined=function(val){return val==null;};elgg.assertTypeOf=function(type,val){if(typeof val!==type){throw new TypeError("Expecting param of "+
arguments.caller+"to be a(n) "+type+"."+"  Was actually a(n) "+typeof val+".");}};elgg.require=function(pkg){elgg.assertTypeOf('string',pkg);var parts=pkg.split('.'),cur=elgg.global,part,i;for(i=0;i<parts.length;i+=1){part=parts[i];cur=cur[part];if(elgg.isUndefined(cur)){throw new Error("Missing package: "+pkg);}}};elgg.provide=function(pkg,opt_context){elgg.assertTypeOf('string',pkg);var parts=pkg.split('.'),context=opt_context||elgg.global,part,i;for(i=0;i<parts.length;i+=1){part=parts[i];context[part]=context[part]||{};context=context[part];}};elgg.inherit=function(Child,Parent){Child.prototype=new Parent();Child.prototype.constructor=Child;};elgg.normalize_url=function(url){url=url||'';elgg.assertTypeOf('string',url);function validate(url){url=elgg.parse_url(url);if(url.scheme){url.scheme=url.scheme.toLowerCase();}
if(url.scheme=='http'||url.scheme=='https'){if(!url.host){return false;}
if(!(new RegExp("^([a-zA-Z0-9][a-zA-Z0-9\\-\\.]*)$","i")).test(url.host)||url.host.charAt(-1)=='.'){return false;}}
if(!url.scheme||!url.host&&url.scheme!='mailto'&&url.scheme!='news'&&url.scheme!='file'){return false;}
return true;};if(url.indexOf('http:')===0||url.indexOf('https:')===0||url.indexOf('javascript:')===0||url.indexOf('mailto:')===0){return url;}
else if(validate(url)){return url;}
else if((new RegExp("^(\\#|\\?|//)","i")).test(url)){return url;}
else if((new RegExp("^[^\/]*\\.php(\\?.*)?$","i")).test(url)){return elgg.config.wwwroot+url.ltrim('/');}
else if((new RegExp("^[^/]*\\.","i")).test(url)){return'http://'+url;}
else{return elgg.config.wwwroot+url.ltrim('/');}};elgg.system_messages=function(msgs,delay,type){if(elgg.isUndefined(msgs)){return;}
var classes=['elgg-message'],messages_html=[],appendMessage=function(msg){messages_html.push('<li class="'+classes.join(' ')+'"><p>'+msg+'</p></li>');},systemMessages=$('ul.elgg-system-messages'),i;delay=parseInt(delay||6000,10);if(isNaN(delay)||delay<=0){delay=6000;}
if(!elgg.isArray(msgs)){msgs=[msgs];}
if(type==='error'){classes.push('elgg-state-error');}else{classes.push('elgg-state-success');}
msgs.forEach(appendMessage);if(type!='error'){$(messages_html.join('')).appendTo(systemMessages).animate({opacity:'1.0'},delay).fadeOut('slow');}else{$(messages_html.join('')).appendTo(systemMessages);}};elgg.system_message=function(msgs,delay){elgg.system_messages(msgs,delay,"message");};elgg.register_error=function(errors,delay){elgg.system_messages(errors,delay,"error");};elgg.deprecated_notice=function(msg,dep_version){if(elgg.is_admin_logged_in()){var parts=elgg.release.split('.');var elgg_major_version=parseInt(parts[0],10);var elgg_minor_version=parseInt(parts[1],10);var dep_major_version=Math.floor(dep_version);var dep_minor_version=10*(dep_version-dep_major_version);msg="Deprecated in Elgg "+dep_version+": "+msg;if((dep_major_version<elgg_major_version)||(dep_minor_version<elgg_minor_version)){elgg.register_error(msg);}else{if(typeof console!=="undefined"){console.warn(msg);}}}};elgg.forward=function(url){location.href=elgg.normalize_url(url);};elgg.parse_url=function(url,component,expand){expand=expand||false;component=component||false;var re_str='^(?:(?![^:@]+:[^:@/]*@)([^:/?#.]+):)?(?://)?'
+'((?:(([^:@]*)(?::([^:@]*))?)?@)?'
+'([^:/?#]*)(?::(\\d*))?)'
+'(((/(?:[^?#](?![^?#/]*\\.[^?#/.]+(?:[?#]|$)))*/?)?([^?#/]*))'
+'(?:\\?([^#]*))?'
+'(?:#(.*))?)',keys={1:"scheme",4:"user",5:"pass",6:"host",7:"port",9:"path",12:"query",13:"fragment"},results={};if(url.indexOf('mailto:')===0){results['scheme']='mailto';results['path']=url.replace('mailto:','');return results;}
if(url.indexOf('javascript:')===0){results['scheme']='javascript';results['path']=url.replace('javascript:','');return results;}
var re=new RegExp(re_str);var matches=re.exec(url);for(var i in keys){if(matches[i]){results[keys[i]]=matches[i];}}
if(expand&&typeof(results['query'])!='undefined'){results['query']=elgg.parse_str(results['query']);}
if(component){if(typeof(results[component])!='undefined'){return results[component];}else{return false;}}
return results;};elgg.parse_str=function(string){var params={},result,key,value,re=/([^&=]+)=?([^&]*)/g,re2=/\[\]$/;while(result=re.exec(string)){key=decodeURIComponent(result[1].replace(/\+/g,' '));value=decodeURIComponent(result[2].replace(/\+/g,' '));if(re2.test(key)){key=key.replace(re2,'');if(!params[key]){params[key]=[];}
params[key].push(value);}else{params[key]=value;}}
return params;};elgg.getSelectorFromUrlFragment=function(url){var fragment=url.split('#')[1];if(fragment){if(fragment.indexOf('.')>-1){return fragment;}
else{return'#'+fragment;}}
return'';};elgg.push_to_object_array=function(object,parent,value){elgg.assertTypeOf('object',object);elgg.assertTypeOf('string',parent);if(!(object[parent]instanceof Array)){object[parent]=[];}
if($.inArray(value,object[parent])<0){return object[parent].push(value);}
return false;};elgg.is_in_object_array=function(object,parent,value){elgg.assertTypeOf('object',object);elgg.assertTypeOf('string',parent);return typeof(object[parent])!='undefined'&&$.inArray(value,object[parent])>=0;};elgg.ElggEntity=function(o){$.extend(this,o);};elgg.ElggUser=function(o){elgg.ElggEntity.call(this,o);};elgg.inherit(elgg.ElggUser,elgg.ElggEntity);elgg.ElggUser.prototype.isAdmin=function(){return this.admin;};elgg.ElggPriorityList=function(){this.length=0;this.priorities_=[];};elgg.ElggPriorityList.prototype.insert=function(obj,opt_priority){var priority=500;if(arguments.length==2&&opt_priority!==undefined){priority=parseInt(opt_priority,10);}
priority=Math.max(priority,0);if(elgg.isUndefined(this.priorities_[priority])){this.priorities_[priority]=[];}
this.priorities_[priority].push(obj);this.length++;};elgg.ElggPriorityList.prototype.forEach=function(callback){elgg.assertTypeOf('function',callback);var index=0;this.priorities_.forEach(function(elems){elems.forEach(function(elem){callback(elem,index++);});});return this;};elgg.ElggPriorityList.prototype.every=function(callback){elgg.assertTypeOf('function',callback);var index=0;return this.priorities_.every(function(elems){return elems.every(function(elem){return callback(elem,index++);});});};elgg.ElggPriorityList.prototype.remove=function(obj){this.priorities_.forEach(function(elems){var index;while((index=elems.indexOf(obj))!==-1){elems.splice(index,1);this.length--;}});};if(!Array.prototype.every){Array.prototype.every=function(callback){var len=this.length,i;for(i=0;i<len;i++){if(i in this&&!callback.call(null,this[i],i)){return false;}}
return true;};}
if(!Array.prototype.forEach){Array.prototype.forEach=function(callback){var len=this.length,i;for(i=0;i<len;i++){if(i in this){callback.call(null,this[i],i);}}};}
if(!String.prototype.ltrim){String.prototype.ltrim=function(str){if(this.indexOf(str)===0){return this.substring(str.length);}else{return this;}};}
elgg.provide('elgg.config.hooks');elgg.provide('elgg.config.instant_hooks');elgg.provide('elgg.config.triggered_hooks');elgg.register_hook_handler=function(name,type,handler,priority){elgg.assertTypeOf('string',name);elgg.assertTypeOf('string',type);elgg.assertTypeOf('function',handler);if(!name||!type){return false;}
var priorities=elgg.config.hooks;elgg.provide(name+'.'+type,priorities);if(!(priorities[name][type]instanceof elgg.ElggPriorityList)){priorities[name][type]=new elgg.ElggPriorityList();}
if(elgg.is_instant_hook(name,type)&&elgg.is_triggered_hook(name,type)){handler(name,type,null,null);}
return priorities[name][type].insert(handler,priority);};elgg.trigger_hook=function(name,type,params,value){elgg.assertTypeOf('string',name);elgg.assertTypeOf('string',type);elgg.set_triggered_hook(name,type);value=!elgg.isNullOrUndefined(value)?value:null;var hooks=elgg.config.hooks,tempReturnValue=null,returnValue=value,callHookHandler=function(handler){tempReturnValue=handler(name,type,params,returnValue);if(!elgg.isNullOrUndefined(tempReturnValue)){returnValue=tempReturnValue;}};elgg.provide(name+'.'+type,hooks);elgg.provide('all.'+type,hooks);elgg.provide(name+'.all',hooks);elgg.provide('all.all',hooks);var hooksList=[];if(name!='all'&&type!='all'){hooksList.push(hooks[name][type]);}
if(type!='all'){hooksList.push(hooks['all'][type]);}
if(name!='all'){hooksList.push(hooks[name]['all']);}
hooksList.push(hooks['all']['all']);hooksList.every(function(handlers){if(handlers instanceof elgg.ElggPriorityList){handlers.forEach(callHookHandler);}
return true;});return returnValue;};elgg.register_instant_hook=function(name,type){elgg.assertTypeOf('string',name);elgg.assertTypeOf('string',type);return elgg.push_to_object_array(elgg.config.instant_hooks,name,type);};elgg.is_instant_hook=function(name,type){return elgg.is_in_object_array(elgg.config.instant_hooks,name,type);};elgg.set_triggered_hook=function(name,type){return elgg.push_to_object_array(elgg.config.triggered_hooks,name,type);};elgg.is_triggered_hook=function(name,type){return elgg.is_in_object_array(elgg.config.triggered_hooks,name,type);};elgg.register_instant_hook('init','system');elgg.register_instant_hook('ready','system');elgg.register_instant_hook('boot','system');elgg.provide('elgg.security.token');elgg.security.tokenRefreshFailed=false;elgg.security.tokenRefreshTimer=null;elgg.security.setToken=function(json){elgg.security.token=json;$('[name=__elgg_ts]').val(json.__elgg_ts);$('[name=__elgg_token]').val(json.__elgg_token);$('[href*="__elgg_ts"][href*="__elgg_token"]').each(function(){this.href=this.href.replace(/__elgg_ts=\d*/,'__elgg_ts='+json.__elgg_ts).replace(/__elgg_token=[0-9a-f]*/,'__elgg_token='+json.__elgg_token);});};elgg.security.refreshToken=function(){elgg.getJSON('refresh_token',function(data){if(data&&data.__elgg_ts&&data.__elgg_token){elgg.security.setToken(data);if(elgg.is_logged_in()&&data.logged_in===false){elgg.session.user=null;elgg.register_error(elgg.echo('session_expired'));}}});};elgg.security.addToken=function(data){if(elgg.isString(data)){var parts=elgg.parse_url(data),args={},base='';if(parts['host']===undefined){if(data.indexOf('?')===0){base='?';args=elgg.parse_str(parts['query']);}}else{if(parts['query']!==undefined){args=elgg.parse_str(parts['query']);}
var split=data.split('?');base=split[0]+'?';}
args["__elgg_ts"]=elgg.security.token.__elgg_ts;args["__elgg_token"]=elgg.security.token.__elgg_token;return base+jQuery.param(args);}
if(elgg.isUndefined(data)){return elgg.security.token;}
if(elgg.isPlainObject(data)){return elgg.extend(data,elgg.security.token);}
throw new TypeError("elgg.security.addToken not implemented for "+(typeof data)+"s");};elgg.security.init=function(){elgg.security.tokenRefreshTimer=setInterval(elgg.security.refreshToken,elgg.security.interval);};elgg.register_hook_handler('boot','system',elgg.security.init);elgg.provide('elgg.config.translations');elgg.config.language='en';elgg.add_translation=function(lang,translations){elgg.provide('elgg.config.translations.'+lang);elgg.extend(elgg.config.translations[lang],translations);};elgg.get_language=function(){var user=elgg.get_logged_in_user_entity();if(user&&user.language){return user.language;}
return elgg.config.language;};elgg.echo=function(key,argv,language){if(elgg.isString(argv)){language=argv;argv=[];}
var translations=elgg.config.translations,dlang=elgg.get_language(),map;language=language||dlang;argv=argv||[];map=translations[language]||translations[dlang];if(map&&map[key]){return vsprintf(map[key],argv);}
return key;};elgg.provide('elgg.ajax');elgg.ajax=function(url,options){options=elgg.ajax.handleOptions(url,options);options.url=elgg.normalize_url(options.url);return $.ajax(options);};elgg.ajax.SUCCESS=0;elgg.ajax.ERROR=-1;elgg.ajax.handleOptions=function(url,options){var data_only=true,data,member;if(elgg.isString(url)){options=options||{};}else{options=url||{};url=options.url;}
if(elgg.isFunction(options)){data_only=false;options={success:options};}
if(options.data){data_only=false;}else{for(member in options){if(elgg.isFunction(options[member])){data_only=false;}}}
if(data_only){data=options;options={data:data};}
if(!elgg.isFunction(options.error)){options.error=function(xhr,status,error){elgg.ajax.handleAjaxError(xhr,status,error);};}
if(url){options.url=url;}
return options;};elgg.ajax.handleAjaxError=function(xhr,status,error){elgg.register_error(elgg.echo('ajax:error'));};elgg.get=function(url,options){options=elgg.ajax.handleOptions(url,options);options.type='get';return elgg.ajax(options);};elgg.getJSON=function(url,options){options=elgg.ajax.handleOptions(url,options);options.dataType='json';return elgg.get(options);};elgg.post=function(url,options){options=elgg.ajax.handleOptions(url,options);options.type='post';return elgg.ajax(options);};elgg.action=function(action,options){elgg.assertTypeOf('string',action);if(action.indexOf('action/')<0){action='action/'+action;}
options=elgg.ajax.handleOptions(action,options);if(!elgg.isString(options.data)||options.data.indexOf('__elgg_ts')==-1){options.data=elgg.security.addToken(options.data);}
options.dataType='json';var custom_success=options.success||elgg.nullFunction;options.success=function(json,two,three,four){if(json&&json.system_messages){elgg.register_error(json.system_messages.error);elgg.system_message(json.system_messages.success);}
custom_success(json,two,three,four);};return elgg.post(options);};elgg.api=function(method,options){elgg.assertTypeOf('string',method);var defaults={dataType:'json',data:{}};options=elgg.ajax.handleOptions(method,options);options=$.extend(defaults,options);options.url='services/api/rest/'+options.dataType+'/';options.data.method=method;return elgg.ajax(options);};elgg.provide('elgg.session');elgg.session.cookie=function(name,value,options){var cookies=[],cookie=[],i=0,date,valid=true;if(elgg.isUndefined(name)){return document.cookie;}
if(elgg.isUndefined(value)){if(document.cookie&&document.cookie!==''){cookies=document.cookie.split(';');for(i=0;i<cookies.length;i+=1){cookie=jQuery.trim(cookies[i]).split('=');if(cookie[0]===name){return decodeURIComponent(cookie[1]);}}}
return undefined;}
options=options||{};if(elgg.isNull(value)){value='';options.expires=-1;}
cookies.push(name+'='+value);if(options.expires){if(elgg.isNumber(options.expires)){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else if(options.expires.toUTCString){date=options.expires;}
if(date){cookies.push('expires='+date.toUTCString());}}
if(options.path){cookies.push('path='+(options.path));}
if(options.domain){cookies.push('domain='+(options.domain));}
if(options.secure){cookies.push('secure');}
document.cookie=cookies.join('; ');};elgg.get_logged_in_user_entity=function(){return elgg.session.user;};elgg.get_logged_in_user_guid=function(){var user=elgg.get_logged_in_user_entity();return user?user.guid:0;};elgg.is_logged_in=function(){return(elgg.get_logged_in_user_entity()instanceof elgg.ElggUser);};elgg.is_admin_logged_in=function(){var user=elgg.get_logged_in_user_entity();return(user instanceof elgg.ElggUser)&&user.isAdmin();};jQuery.cookie=elgg.session.cookie;if(elgg.session.user){elgg.session.user=new elgg.ElggUser(elgg.session.user);}
elgg.get_page_owner_guid=function(){if(elgg.page_owner!==undefined){return elgg.page_owner.guid;}else{return 0;}};elgg.provide('elgg.config');elgg.get_site_url=function(){return elgg.config.wwwroot;};elgg.get_simplecache_url=function(view,subview){var lastcache,path;if(elgg.config.simplecache_enabled){lastcache=elgg.config.lastcache;}else{lastcache=0;}
if(!subview){path='/cache/'+lastcache+'/'+elgg.config.viewtype+'/'+view;}else{if((view==='js'||view==='css')&&0===subview.indexOf(view+'/')){subview=subview.substr(view.length+1);}
path='/cache/'+lastcache+'/'+elgg.config.viewtype+'/'+view+'/'+subview;}
return elgg.normalize_url(path);};elgg.provide('elgg.comments');elgg.comments.Comment=function(guid){this.guid=guid;this.$item=$('#elgg-object-'+guid);};elgg.comments.Comment.prototype={getForm:function(){return this.$item.find('.elgg-form-comment-save');},hideForm:function(complete){complete=complete||function(){};this.getForm().slideUp('fast',complete).data('hidden',1);},showForm:function(){this.getForm().slideDown('medium').data('hidden',0);},loadForm:function(){var that=this;elgg.ajax('ajax/view/core/ajax/edit_comment?guid='+this.guid,{success:function(html){that.$item.find('.elgg-body').first().append(html);that.showForm();var $form=that.getForm();$form.find('.elgg-button-cancel').on('click',function(){that.hideForm();return false;});$form.on('submit',function(){that.submitForm();return false;});}});},submitForm:function(){var that=this,$form=this.getForm(),value=$form.find('textarea[name=generic_comment]').val();elgg.action('comment/save',{data:$form.serialize(),success:function(json){function nl2br(content){if(/<(?:p|br)\b/.test(content)){return content;}
return content.replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,'$1<br>$2');}
if(json.status===0){if(json.output){that.$item.find('[data-role="comment-text"]').replaceWith(json.output);}else{that.$item.find('[data-role="comment-text"]').html(nl2br(value));}}
that.hideForm(function(){that.getForm().remove();});}});return false;},toggleEdit:function(){var $form=this.getForm();if($form.length){if($form.data('hidden')){this.showForm();}else{this.hideForm();}}else{this.loadForm();}
return false;}};elgg.comments.init=function(){$(document).on('click','.elgg-item-object-comment .elgg-menu-item-edit > a',function(){var dc=$(this).data('Comment'),guid;if(!dc){guid=this.href.split('/').pop();dc=new elgg.comments.Comment(guid);$(this).data('Comment',dc);}
dc.toggleEdit();return false;});};elgg.register_hook_handler('init','system',elgg.comments.init);elgg.provide('elgg.ui');elgg.ui.init=function(){$('.elgg-page').attr("onclick","return true");elgg.ui.initHoverMenu();$(document).on('click','.elgg-system-messages li',function(){$(this).stop().fadeOut('fast');});$('.elgg-system-messages li').animate({opacity:0.9},6000);$('.elgg-system-messages li.elgg-state-success').fadeOut('slow');$(document).on('click','[rel=toggle]',elgg.ui.toggles);$(document).on('click','[rel=popup]',elgg.ui.popupOpen);$(document).on('click','.elgg-menu-page .elgg-menu-parent',elgg.ui.toggleMenu);$(document).on('click','*[data-confirm], .elgg-requires-confirmation',elgg.ui.requiresConfirmation);if($('.elgg-requires-confirmation').length>0){elgg.deprecated_notice('Use of .elgg-requires-confirmation is deprecated by data-confirm','1.10');}
$('.elgg-autofocus').focus();if($('.elgg-autofocus').length>0){elgg.deprecated_notice('Use of .elgg-autofocus is deprecated by html5 autofocus',1.9);}
elgg.ui.initAccessInputs();var elementId=elgg.getSelectorFromUrlFragment(document.URL);$(elementId).addClass('elgg-state-highlight');};elgg.ui.toggles=function(event){event.preventDefault();var $this=$(this),target=$this.data().toggleSelector;if(!target){target=$this.attr('href');}
$this.toggleClass('elgg-state-active');$(target).each(function(index,elem){var $elem=$(elem);if($elem.data().toggleSlide!=false){$elem.slideToggle('medium');}else{$elem.toggle();}});};elgg.ui.popupOpen=function(event){event.preventDefault();event.stopPropagation();var target=elgg.getSelectorFromUrlFragment($(this).toggleClass('elgg-state-active').attr('href'));var $target=$(target);var params={targetSelector:target,target:$target,source:$(this)};var options={my:'center top',at:'center bottom',of:$(this),collision:'fit fit'};options=elgg.trigger_hook('getOptions','ui.popup',params,options);if(!options){return;}
if($target.is(':visible')){$target.fadeOut();$('body').die('click',elgg.ui.popupClose);return;}
$target.appendTo('body').fadeIn().position(options);$(document).off('click','body',elgg.ui.popupClose).on('click','body',elgg.ui.popupClose);};elgg.ui.popupClose=function(event){$eventTarget=$(event.target);var inTarget=false;var $popups=$('[rel=popup]');$popups.each(function(i,e){var target=elgg.getSelectorFromUrlFragment($(e).attr('href'))+':visible';var $target=$(target);if(!$target.is(':visible')){return;}
if($eventTarget.closest(target).length>0){inTarget=true;return false;}});if(!inTarget){$popups.each(function(i,e){var $e=$(e);var $target=$(elgg.getSelectorFromUrlFragment($e.attr('href'))+':visible');if($target.length>0){$target.fadeOut();$e.removeClass('elgg-state-active');}});$('body').die('click',elgg.ui.popClose);}};elgg.ui.toggleMenu=function(event){$(this).siblings().slideToggle('medium');$(this).toggleClass('elgg-menu-closed elgg-menu-opened');event.preventDefault();};elgg.ui.initHoverMenu=function(parent){function loadMenu(mac){var $all_placeholders=$(".elgg-menu-hover[rel='"+mac+"']");var $ul=$all_placeholders.filter('[data-elgg-menu-data]');if(!$ul.length){return;}
elgg.get('ajax/view/navigation/menu/user_hover/contents',{data:$ul.data('elggMenuData'),success:function(data){if(data){$all_placeholders.removeClass('elgg-ajax-loader').html($(data).children());}}});}
if(!parent){parent=document;}
$(parent).on('mouseover',".elgg-avatar",function(){$(this).children(".elgg-icon-hover-menu").show();}).on('mouseout','.elgg-avatar',function(){$(this).children(".elgg-icon-hover-menu").hide();});$(document).on('click',".elgg-avatar > .elgg-icon-hover-menu",function(e){var $placeholder=$(this).parent().find(".elgg-menu-hover.elgg-ajax-loader");if($placeholder.length){loadMenu($placeholder.attr("rel"));}
var $hovermenu=$(this).data('hovermenu')||null;if(!$hovermenu){$hovermenu=$(this).parent().find(".elgg-menu-hover");$(this).data('hovermenu',$hovermenu);}
if($hovermenu.css('display')=="block"){$hovermenu.fadeOut();}else{$avatar=$(this).closest(".elgg-avatar");var offset=$avatar.offset();var top=$avatar.height()+offset.top+'px';var left=$avatar.width()-15+offset.left+'px';$hovermenu.appendTo('body').css('position','absolute').css("top",top).css("left",left).fadeIn('normal');}
$(".elgg-menu-hover:visible").not($hovermenu).fadeOut();});$(document).click(function(event){if($(event.target).parents(".elgg-avatar").length===0){$(".elgg-menu-hover").fadeOut();}});};elgg.ui.requiresConfirmation=function(e){var confirmText=$(this).data('confirm')||elgg.echo('question:areyousure');if(!confirm(confirmText)){e.preventDefault();}};elgg.ui.loginHandler=function(hook,type,params,options){if(params.target.attr('id')=='login-dropdown-box'){options.my='right top';options.at='right bottom';return options;}
return null;};elgg.ui.initDatePicker=function(){function loadDatePicker(){$('.elgg-input-date').datepicker({dateFormat:'yy-mm-dd',onSelect:function(dateText){if($(this).is('.elgg-input-timestamp')){var dateParts=dateText.split("-");var timestamp=Date.UTC(dateParts[0],dateParts[1]-1,dateParts[2]);timestamp=timestamp/1000;var id=$(this).attr('id');$('input[name="'+id+'"]').val(timestamp);}},nextText:'&#xBB;',prevText:'&#xAB;',changeMonth:true,changeYear:true});}
if(!$('.elgg-input-date').length){return;}
var deps=[];if(elgg.get_language()!='en'){deps.push('jquery-ui/i18n/datepicker-'+elgg.get_language()+'.min');}
require(deps,loadDatePicker);};elgg.ui.registerTogglableMenuItems=function(menuItemNameA,menuItemNameB){$(document).off('click.togglable','.elgg-menu-item-'+menuItemNameA+' a').on('click.togglable','.elgg-menu-item-'+menuItemNameA+' a',function(){var $menu=$(this).closest('.elgg-menu');elgg.ui.toggleMenuItems($menu,menuItemNameB,menuItemNameA);elgg.action($(this).attr('href'),{success:function(json){if(json.system_messages.error.length){elgg.ui.toggleMenuItems($menu,menuItemNameA,menuItemNameB);}},error:function(){elgg.ui.toggleMenuItems($menu,menuItemNameA,menuItemNameB);}});return false;});$(document).off('click.togglable','.elgg-menu-item-'+menuItemNameB+' a').on('click.togglable','.elgg-menu-item-'+menuItemNameB+' a',function(){var $menu=$(this).closest('.elgg-menu');elgg.ui.toggleMenuItems($menu,menuItemNameA,menuItemNameB);elgg.action($(this).attr('href'),{success:function(json){if(json.system_messages.error.length){elgg.ui.toggleMenuItems($menu,menuItemNameB,menuItemNameA);}},error:function(){elgg.ui.toggleMenuItems($menu,menuItemNameB,menuItemNameA);}});return false;});};elgg.ui.toggleMenuItems=function($menu,nameOfItemToShow,nameOfItemToHide){$menu.find('.elgg-menu-item-'+nameOfItemToShow).removeClass('hidden').find('a').focus();$menu.find('.elgg-menu-item-'+nameOfItemToHide).addClass('hidden');};elgg.ui.initAccessInputs=function(){$('.elgg-input-access').each(function(){function updateMembersonlyNote(){var val=$select.val();if(val!=acl&&val!==0){$note.css('visibility','visible');}else{$note.css('visibility','hidden');}}
var $select=$(this),acl=$select.data('group-acl'),$note=$('.elgg-input-access-membersonly',this.parentNode),commentCount=$select.data('comment-count'),originalValue=$select.data('original-value');if($note){updateMembersonlyNote();$select.change(updateMembersonlyNote);}
if(commentCount){$select.change(function(e){if($(this).val()!=originalValue){if(!confirm(elgg.echo('access:comments:change',[commentCount]))){$(this).val(originalValue);}}});}});};elgg.register_hook_handler('init','system',elgg.ui.init);elgg.register_hook_handler('init','system',elgg.ui.initDatePicker);elgg.register_hook_handler('getOptions','ui.popup',elgg.ui.loginHandler);elgg.ui.registerTogglableMenuItems('add-friend','remove-friend');elgg.provide('elgg.ui.widgets');elgg.ui.widgets.init=function(){if($(".elgg-widgets").length===0){return;}
$(".elgg-widgets").sortable({items:'div.elgg-module-widget.elgg-state-draggable',connectWith:'.elgg-widgets',handle:'.elgg-widget-handle',forcePlaceholderSize:true,placeholder:'elgg-widget-placeholder',opacity:0.8,revert:500,stop:elgg.ui.widgets.move});$('.elgg-widgets-add-panel li.elgg-state-available').click(elgg.ui.widgets.add);$(document).on('click','a.elgg-widget-delete-button',elgg.ui.widgets.remove);$(document).on('submit','.elgg-widget-edit > form ',elgg.ui.widgets.saveSettings);$(document).on('click','a.elgg-widget-collapse-button',elgg.ui.widgets.collapseToggle);elgg.ui.widgets.setMinHeight(".elgg-widgets");};elgg.ui.widgets.add=function(event){var type=$(this).data('elgg-widget-type');var multiple=$(this).attr('class').indexOf('elgg-widget-multiple')!=-1;if(multiple===false){$(this).addClass('elgg-state-unavailable');$(this).removeClass('elgg-state-available');$(this).unbind('click',elgg.ui.widgets.add);}
elgg.action('widgets/add',{data:{handler:type,page_owner_guid:elgg.get_page_owner_guid(),context:$("input[name='widget_context']").val(),show_access:$("input[name='show_access']").val(),default_widgets:$("input[name='default_widgets']").val()||0},success:function(json){$('#elgg-widget-col-1').prepend(json.output);}});event.preventDefault();};elgg.ui.widgets.move=function(event,ui){var guidString=ui.item.attr('id');guidString=guidString.substr(guidString.indexOf('elgg-widget-')+"elgg-widget-".length);var col=ui.item.parent().attr('id');col=col.substr(col.indexOf('elgg-widget-col-')+"elgg-widget-col-".length);elgg.action('widgets/move',{data:{widget_guid:guidString,column:col,position:ui.item.index()}});ui.item.css('top',0);ui.item.css('left',0);};elgg.ui.widgets.remove=function(event){if(confirm(elgg.echo('deleteconfirm'))===false){event.preventDefault();return;}
var $widget=$(this).closest('.elgg-module-widget');var type=$(this).data('elgg-widget-type');$container=$(this).parents('.elgg-layout-widgets').first();$button=$('[data-elgg-widget-type="'+type+'"]',$container);var multiple=$button.attr('class').indexOf('elgg-widget-multiple')!=-1;if(multiple===false){$button.addClass('elgg-state-available');$button.removeClass('elgg-state-unavailable');$button.unbind('click',elgg.ui.widgets.add);$button.click(elgg.ui.widgets.add);}
$widget.remove();elgg.action($(this).attr('href'));event.preventDefault();};elgg.ui.widgets.collapseToggle=function(event){$(this).toggleClass('elgg-widget-collapsed');$(this).parent().parent().find('.elgg-body').slideToggle('medium');event.preventDefault();};elgg.ui.widgets.saveSettings=function(event){$(this).parent().slideToggle('medium');var $widgetContent=$(this).parent().parent().children('.elgg-widget-content');var $loader=$('#elgg-widget-loader').clone();$loader.attr('id','#elgg-widget-active-loader');$loader.removeClass('hidden');$widgetContent.html($loader);var default_widgets=$("input[name='default_widgets']").val()||0;if(default_widgets){$(this).append('<input type="hidden" name="default_widgets" value="1">');}
elgg.action('widgets/save',{data:$(this).serialize(),success:function(json){$widgetContent.html(json.output);if(typeof(json.title)!="undefined"){var $widgetTitle=$widgetContent.parent().parent().find('.elgg-widget-title');$widgetTitle.html(json.title);}}});event.preventDefault();};elgg.ui.widgets.setMinHeight=function(selector){var maxBottom=0;$(selector).each(function(){var bottom=parseInt($(this).offset().top+$(this).height());if(bottom>maxBottom){maxBottom=bottom;}});$(selector).each(function(){var bottom=parseInt($(this).offset().top+$(this).height());if(bottom<maxBottom){var newMinHeight=parseInt($(this).height()+(maxBottom-bottom));$(this).css('min-height',newMinHeight+'px');}});};elgg.register_hook_handler('init','system',elgg.ui.widgets.init);elgg.version='2015062900';elgg.release='2.0.1';elgg.config.wwwroot='http://localhost/elgg-2.0.1/';elgg.security.interval=2397600;elgg.config.language='en';define('jquery',function(){return jQuery;});define('jquery-ui');define('jquery-ui/datepicker',jQuery.datepicker);define('elgg',['jquery','languages/'+elgg.get_language()],function($,translations){elgg.add_translation(elgg.get_language(),translations);$(function(){elgg.trigger_hook('init','system');elgg.trigger_hook('ready','system');});return elgg;});require(['elgg']);if(!window._require_queue){if(window.console){console.log('Elgg\'s require() shim is not defined. Do not override the view "page/elements/head".');}}else{while(_require_queue.length){require.apply(null,_require_queue.shift());}
delete window._require_queue;}
elgg.trigger_hook('boot','system');elgg.register_hook_handler('init','system',function(){if($('.profile').length){$('#elgg-widget-col-1').css('min-height',$('.profile').outerHeight(true)+1);}},400);CKEDITOR_BASEPATH=elgg.config.wwwroot+'mod/ckeditor/vendors/ckeditor/';elgg.ui.registerTogglableMenuItems('feature','unfeature');elgg.ui.likesPopupHandler=function(hook,type,params,options){if(params.target.hasClass('elgg-likes')){options.my='right bottom';options.at='left top';return options;}
return null;};elgg.register_hook_handler('getOptions','ui.popup',elgg.ui.likesPopupHandler);!function(){function setupHandlers(nameA,nameB){$(document).on('click','.elgg-menu-item-'+nameA+' a',function(){var $menu=$(this).closest('.elgg-menu');elgg.ui.toggleMenuItems($menu,nameB,nameA);$menu.find('.elgg-menu-item-'+nameB+' a').blur();elgg.action($(this).attr('href'),{success:function(data){if(data.system_messages.error.length){elgg.ui.toggleMenuItems($menu,nameA,nameB);}
var func_name=data.output.num_likes>0?'removeClass':'addClass';$(data.output.selector).text(data.output.text)[func_name]('hidden');},error:function(){elgg.ui.toggleMenuItems($menu,nameA,nameB);}});return false;});}
setupHandlers('likes','unlike');setupHandlers('unlike','likes');}();elgg.register_hook_handler('init','system',function(){$("#messages-toggle").click(function(){$('input[type=checkbox]').click();});});elgg.provide('elgg.uservalidationbyemail');elgg.uservalidationbyemail.init=function(){$('#uservalidationbyemail-checkall').click(function(){$('#uservalidationbyemail-form .elgg-body').find('input[type=checkbox]').prop('checked',this.checked);});$('.uservalidationbyemail-submit').click(function(event){var form=$('#uservalidationbyemail-form')[0];event.preventDefault();if($('.elgg-body',form).find('input[type=checkbox]:checked').length<1){return false;}
if(!confirm(this.title)){return false;}
form.action=this.href;form.submit();});};elgg.register_hook_handler('init','system',elgg.uservalidationbyemail.init);elgg.provide('elgg.rate');elgg.rate.init=function(){var form=$('.elgg-form-rate-rate');form.find('input[type=submit]').live('click',elgg.rate.submit);};elgg.rate.submit=function(e){var form=$(this).parents('form');var data=form.serialize();elgg.action('rate/rate',{data:data+"&ajax=1",success:function(json){var html=json.output;form.html(html);}});e.preventDefault();};elgg.register_hook_handler('init','system',elgg.rate.init);elgg.ui.registerTogglableMenuItems('follow-tag-on','follow-tag-off');$(document).ready(function(){$('#live_notifications_loader').show();$("#live_notifications_link").click(function(){var num=parseInt($("#count_unread_notifications").html());if(num>0){elgg.action('live_notifications/read_all',function(response){});$('.elgg-icon-live_notifications').removeClass("elgg-icon-live_notifications-selected");}
$("#count_unread_notifications").html(0);$("#count_unread_notifications").hide();});if(elgg.is_logged_in()){$("#live_notifications_result").load("http://localhost/elgg-2.0.1/live_notifications/ajax",function(){$('#live_notifications_loader').hide();});setInterval(function(){elgg.action('live_notifications/refresh_count',function(response){var num=parseInt($("#count_unread_notifications").html());var new_count=parseInt(response.output);if(new_count>num){$("#count_unread_notifications").show();$("#count_unread_notifications").html(new_count);$('#live_notifications_loader').show();$("#live_notifications_result").load("http://localhost/elgg-2.0.1/live_notifications/ajax",function(){$('#live_notifications_loader').hide();elgg.system_message('You have a new notification');});}
else if(new_count==0){$("#count_unread_notifications").hide();}});},10000);setInterval(function(){elgg.action('live_notifications/refresh_count_messages',function(data){var icon=$(".elgg-menu-item-messages");var text='<span class="elgg-icon-mail elgg-icon fa fa-envelope-o"></span>';var num_messages=parseInt(data.output);var num=parseInt($(".elgg-menu-item-messages a span.messages-new").html());if(num_messages>num||num_messages>0){text=text+"<span class=\"messages-new\">"+num_messages+"</span>";$(".elgg-menu-item-messages a").html(text);}
else if(num_messages==0){$(".elgg-menu-item-messages a span.messages-new").hide();}});},15000);}});