define(function(require){var $=require('jquery');var ui=require('jquery-ui');var elgg=require('elgg');var spinner=require('elgg/spinner');function init(){$('.elgg-system-messages li').stop(true);$(document).off('click','.elgg-system-messages li');$(document).on('click','.elgg-system-messages li',function(){$(this).stop().slideUp('medium');});$('#elgg-plugin-list > ul').sortable({items:'li:has(> .elgg-state-draggable)',handle:'.elgg-head',forcePlaceholderSize:true,placeholder:'elgg-widget-placeholder',opacity:0.8,revert:500,stop:movePlugin});$(".elgg-state-editable").editable(editProfileField,{type:'text',onblur:'submit',width:'300px',height:'none',style:'display:inline;'});$('#elgg-profile-fields').sortable({items:'li',handle:'span.elgg-state-draggable',stop:moveProfileField});$('a.elgg-admin-notice').click(deleteNotice);$(document).on('click','input:checkbox.elgg-state-disabled, label.elgg-state-disabled > input:checkbox',function(){return false;});$('[name=simplecache_enabled]').click(simplecacheToggle);$(document).on('click','.elgg-admin-plugins-categories a',filterPluginCategory);$(document).on('click','.elgg-plugin-details-container > ul a',showPluginDetails);$(document).on('click','.elgg-plugins-toggle',toggleAllPlugins);$(document).on('mouseenter','.elgg-plugin-details-screenshots .elgg-plugin-screenshot',showPluginScreenshot);}
function toggleAllPlugins(e){e.preventDefault();if(!confirm(elgg.echo('question:areyousure'))){return;}
var guids=[],state=$(this).data('desiredState'),find_state=state=='active'?'inactive':'active';$('.elgg-plugin.elgg-state-'+find_state+':visible').each(function(){var guid=$(this).data('guid');if(guid){guids.push(guid);}});if(!guids.length){elgg.register_error(elgg.echo('admin:plugins:already:'+state));return;}
spinner.start();var $form=$('<form method="post" />');$form.prop('action',elgg.security.addToken(this.href));$form.append('<input type="hidden" name="guids" value="'+guids.join(',')+'" />');$form.trigger('submit');}
function movePlugin(e,ui){var pluginGuid=ui.item.attr('id');pluginGuid=pluginGuid.replace('elgg-object-','');elgg.action('admin/plugins/set_priority',{data:{plugin_guid:pluginGuid,priority:ui.item.index()+1},success:function(){var priorityDep=new RegExp(elgg.echo('ElggPlugin:Dependencies:Priority'));ui.item.siblings().andSelf().each(function(){if(priorityDep.test($(this).find('.elgg-dependency-requires').text())){updatePluginView($(this));}});}});}
function updatePluginView(pluginView){var pluginGuid=pluginView.attr('id');pluginGuid=pluginGuid.replace('elgg-object-','');elgg.get({url:elgg.config.wwwroot+"ajax/view/object/plugin/full",dataType:"html",cache:false,data:{guid:pluginGuid,display_reordering:true},success:function(htmlData){if(htmlData.length>0){pluginView.html(htmlData);}}});}
function editProfileField(value,settings){var id=$(this).attr('id');id=id.replace('elgg-profile-field-','');var data={id:id,label:value};elgg.action('profile/fields/edit',data);return value;}
function moveProfileField(e,ui){var orderArr=$('#elgg-profile-fields').sortable('toArray');var orderStr=orderArr.join(',');elgg.action('profile/fields/reorder',{fieldorder:orderStr});}
function deleteNotice(e){e.preventDefault();var $container=$(this).closest('p');elgg.action($(this).attr('href'),{success:function(json){$container.slideUp('medium');}});}
function simplecacheToggle(){if(!$(this).hasClass('elgg-state-disabled')){var names=['simplecache_minify_js','simplecache_minify_css'];for(var i=0;i<names.length;i++){var $input=$('input[type!=hidden][name="'+names[i]+'"]');if($input.length){$input.parent().toggleClass('elgg-state-disabled');}}}}
function filterPluginCategory(e){e.preventDefault();$(".elgg-admin-plugins-categories > li").removeClass("elgg-state-selected");$(".elgg-plugin").hide();$(".elgg-plugin-category-"+$(this).attr("rel")).show();$(this).closest('li').addClass("elgg-state-selected");}
function showPluginDetails(){$(".elgg-plugin-details-container > ul > li").removeClass("elgg-state-selected");$(".elgg-plugin-details-container > div > div").hide();$(".elgg-plugin-details-container ."+$(this).attr("rel")).show();$(this).parent().addClass("elgg-state-selected");}
function showPluginScreenshot(){$(this).parent().find(".elgg-plugin-screenshot").removeClass("elgg-state-selected");$(this).addClass("elgg-state-selected");$(".elgg-plugin-details-screenshots > div > img").hide();$(".elgg-plugin-details-screenshots > div > img[rel='"+$(this).attr("rel")+"']").show();}
init();});